### ISSUE TITLE
IntelliJ menu/application bar missing on secondary project windows

### ISSUE THREAD

**Issue by DW8Reaper** [pop-os/cosmic-comp#1029]
In cosmic if I open multiple intellij projects only the first project window I opened has the main application toolbar and subsequent ones don't, for example:
![cosmic](https://github.com/user-attachments/assets/bb57355e-361e-468c-8443-e7feb4e304ee)

This might be an intellij issue but the same scenario works fine in Pop and also in Pop on wayland:
![pop-on-wayland](https://github.com/user-attachments/assets/d1b42f96-3310-400a-a178-03a1c7841d31)

I'm not sure when this started happening but as I recall around Alpha 2 this wasn't a problem for me I also cannot find any Intellij setting/option to get the menu back. 

Intellij Version (I am using the snap package):

```
➜  ~ snap list
Name                         Version                     Rev    Tracking       Publisher      Notes
intellij-idea-ultimate       2024.3                      548    latest/stable  jetbrains✓     classic
```

Cosmic version:

```
Package: cosmic-comp
Version: 0.1~1733165405~22.04~e3b41c5
Priority: optional
Section: x11
Maintainer: Victoria Brekenfeld <victoria@system76.com>
Installed-Size: 25.2 MB
Depends: libc6 (>= 2.35), libgbm1 (>= 21.3.0~rc1), libgcc-s1 (>= 4.2), libinput10 (>= 1.19.1), libpixman-1-0 (>= 0.30.0), libseat1 (>= 0.5.0), libudev1 (>= 183), libxkbcommon0 (>= 0.5.0), libegl1, libwayland-server0
Recommends: cosmic-session, libgl1-mesa-dri
Homepage: https://github.com/pop-os/cosmic-comp
Download-Size: 7,968 kB
APT-Manual-Installed: no
APT-Sources: http://apt.pop-os.org/release jammy/main amd64 Packages
Description: Wayland compositor of pop-os cosmic shell
```

**Comment by Shepherdsinan** [comment]
I am experiencing the same issue in "JetBrains Rider"

**Comment by DW8Reaper** [comment]
@Shepherdsinan I had another IntelliJ issue and the suggested work around here https://github.com/pop-os/cosmic-comp/issues/874#issuecomment-2718858408 also resolved this header issue for me.

**Comment by DW8Reaper** [comment]
Just wanted to give an update this is still an issue on the latest cosmic-comp:

```bash
Package: cosmic-comp
Version: 0.1~1757920380~24.04~b83e9f1
Priority: optional
Section: x11
Maintainer: Victoria Brekenfeld <victoria@system76.com>
Installed-Size: 26.3 MB
Depends: libc6 (>= 2.39), libdisplay-info1 (>= 0.1.1), libgbm1 (>= 21.3.0~rc1), libgcc-s1 (>= 4.2), libinput10 (>= 1.19.1), libpixman-1-0 (>= 0.30.0), libseat1 (>= 0.5.0), libudev1 (>= 183), libxkbcommon0 (>= 0.5.0), libegl1, libwayland-server0
Recommends: cosmic-session, libgl1-mesa-dri
Homepage: https://github.com/pop-os/cosmic-comp
Download-Size: 8,186 kB
APT-Manual-Installed: no
APT-Sources: http://apt.pop-os.org/release noble/main amd64 Packages
Description: Wayland compositor of pop-os cosmic shell
```

**Comment by ivanbulanov** [comment]
For me the problem was solved. In custom WM options string  "-Dawt.toolkit.name=WLToolkit" was concatenated with another option. I put it on its own line and restarted the IDE.

**Comment by D01B0EB** [comment]
I got the same in RustRover..
Just FYI: [Wayland By Default in 2026.1 EAP](https://blog.jetbrains.com/platform/2026/02/wayland-by-default-in-2026-1-eap/)

X11 is still supported

In a Linux desktop environment that does not support Wayland, IntelliJ-based IDEs will continue to work as X applications. It is also possible to switch to using X11 on any Wayland desktop because an X.Org implementation called XWayland is always available for compatibility with older applications. To do that, add `-Dawt.toolkit.name=XToolkit` to the VM options list `(Help | Edit Custom VM Options…)` and restart the IDE.

Native Wayland support is mostly concentrated in one subsystem called WLToolkit. If you were one of the early adopters of this mode, you had to specify the `-Dawt.toolkit.name=WLToolkit` VM option manually. This will continue to work, but it is no longer necessary.

The launcher will supply a new option to the IDE: -Dawt.toolkit.name=auto. The “auto” option will be resolved into either WLToolkit or XToolkit based on the following rule:

    If wl_display_connect() succeeds, “auto” is replaced with WLToolkit, and therefore the application is launched in the native Wayland mode.
    Otherwise, “auto” is replaced with XToolkit, and the application is launched in X11 mode.

**Comment by D01B0EB** [comment]
This is strange, but RustRover (flatpak ) can't start with Wayland option.

~/.var/app/com.jetbrains.RustRover/config/JetBrains/RustRover2025.3/rustrover64.vmoptions
```
# custom RustRover VM options (expand/override 'bin/rustrover64.vmoptions')
-Dawt.toolkit.name=WLToolkit
```

```
herurg@pop-os:~$ flatpak run com.jetbrains.RustRover
rustrover-wrapper: Setting up NPM packages
rustrover-wrapper: Setting up Cargo packages
rustrover-wrapper: Setting up Python packages
rustrover-wrapper: 'ruby' is not available

**Start Failed**

Internal error

java.awt.HeadlessException:
Could not connect to the Wayland server (check WAYLAND_DISPLAY),
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.dnd.DragSource.getDefaultDragSource(DragSource.java:226)
	at com.intellij.platform.ide.bootstrap.UiKt$scheduleUpdateFrameClassAndWindowIconAndPreloadSystemFonts$1$3.invokeSuspend(ui.kt:265)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:300)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

-----
JRE: 21.0.10+7-b1163.108 amd64 (JetBrains s.r.o.)
/app/extra/rustrover/jbr
```
At the same time RustRover (tar.gz) with `-Dawt.toolkit.name=WLToolkit` start succesfully and works well.

~/.config/JetBrains/RustRover2025.3/rustrover64.vmoptions
```
# custom RustRover VM options (expand/override 'bin/rustrover64.vmoptions'
-Dawt.toolkit.name=WLToolkit
```
