### ISSUE TITLE
Crash with Displaylink dock attached / upon attaching

### ISSUE THREAD

**Issue by MHoogesteger** [pop-os/cosmic-comp#144]
I've just installed cosmic and tried running it with a displaylink dock connected on a fresh Pop install, but get a crash to gray screen and eventually I see the laptop manufacturers BIOS/UEFI startup logo. Attaching the dock after login causes the same thing.

It runs fine without the displaylink dock. Pop on Wayland runs fine with it.

Installed through apt and not too savy with linux in general, but cat /var/log/syslog | grep cosmic gives me the attached log file. It contains both sessions.
[cosmic_log.txt](https://github.com/pop-os/cosmic-comp/files/12242397/cosmic_log.txt)

Issue #136 seems to be crashing on the same unwrap function?

I've also attached the drm_info output.
[drm_info.txt](https://github.com/pop-os/cosmic-comp/files/12242452/drm_info.txt)

**Comment by Drakulix** [comment]
Right, DisplayLink devices are drm-devices without a render-node, which is essentially the same problem, that some virtual GPUs have (like #136).

We need to offload the rendering another GPU (or for the virtual case to some software renderer like llvmpipe) in this case, which cosmic-comp doesn't currently support.

**Comment by juhp** [comment]
Cosmic also crashes for me when I disconnect my Lenovo USB-C Dock.
I am assuming this is the same problem or related - otherwise I can open a new ticket.

**Comment by Drakulix** [comment]
> Cosmic also crashes for me when I disconnect my Lenovo USB-C Dock.

Does it work before you disconnect it? If so, no this isn't related. Please open a new issue and please also post the output of `drm_info`, so we can check how this dock connects internally to our system and what might cause the crash.

**Comment by zsilet** [comment]
I just came across this same issue on the pop_os 24.04 Alpha1 install. 
My system started crashing immediately after installation of the latest displaylink 6.0 driver package from Synaptic. 
Will monitor this issue and will be happy to test once SW rendering becomes available.

**Comment by squalou** [comment]
For the records, tested on different flavor of dell displaylink docks, same thing (as expected). Plug, crash, relaunch, crash immediately. Keeping an eye on this issue as well :)

**Comment by ChadAPSheridan** [comment]
I have to say, I've fallen in love with CosmicDE, but I got a new work laptop, and it uses a displaylink dock, and now I have to use a different DE until this is sorted.  Sadly no other DE's have the feature set I've grown to love in cosmic thus far.  I'll be watching this like a hawk.

**Comment by mnipshagen** [comment]
I am in a similar position with a work laptop using dell displaylink docks crashing the cosmic desktop. Looking forward to this being fixed! It's such a great DE :)

**Comment by ChadAPSheridan** [comment]
Decided to test again to see if it's working yet, still no joy, this is what I'm seeing in the journal, don't know if it will help:
```
Apr 16 12:57:49 Taobh-Solais cosmic-comp[20905]: thread 'surface-DVI-I-1' panicked at 'overflow in iter::sum over durations': /usr/src/debug/rust/rustc-1.85.0-src/library/core/src/time.rs:1225
                                                    0: <unknown>
                                                    1: <unknown>
                                                    2: <unknown>
                                                    3: <unknown>
                                                    4: <unknown>
                                                    5: <unknown>
                                                    6: <unknown>
                                                    7: <unknown>
                                                    8: <unknown>
                                                    9: <unknown>
                                                   10: <unknown>
                                                   11: <unknown>
                                                   12: <unknown>
                                                   13: <unknown>
                                                   14: <unknown>
                                                   15: <unknown>
                                                   16: <unknown>
                                                   17: <unknown>
                                                   18: <unknown>
                                                   19: <unknown>
Apr 16 12:57:49 Taobh-Solais cosmic-comp[20905]: thread 'surface-DVI-I-2' panicked at 'overflow in iter::sum over durations': /usr/src/debug/rust/rustc-1.85.0-src/library/core/src/time.rs:1225
                                                    0: <unknown>
                                                    1: <unknown>
                                                    2: <unknown>
                                                    3: <unknown>
                                                    4: <unknown>
                                                    5: <unknown>
                                                    6: <unknown>
                                                    7: <unknown>
                                                    8: <unknown>
                                                    9: <unknown>
                                                   10: <unknown>
                                                   11: <unknown>
                                                   12: <unknown>
                                                   13: <unknown>
                                                   14: <unknown>
                                                   15: <unknown>
                                                   16: <unknown>
                                                   17: <unknown>
                                                   18: <unknown>
                                                   19: <unknown>
```

**Comment by Shellmade** [comment]
Just started using the Cosmic DE aswell. I've been experiencing the same issues using a Thinkpad Docking station. 
Alternatively, using a satechi dock doesnt seem to cause this issue. Figured this information might be useful for some. 

Does anyone know if this was fixed, or adressed?

**Comment by ChadAPSheridan** [comment]
> 
> Just started using the Cosmic DE aswell. I've been experiencing the same issues using a Thinkpad Docking station. 
> Alternatively, using a satechi dock doesnt seem to cause this issue. Figured this information might be useful for some. 
> 
> Does anyone know if this was fixed, or adressed?
> 
> 

It is definitely not fixed, and hasn't had a comment from the dev team on timelines or plans to fix in a very long time.

**Comment by squalou** [comment]
From personal experience : it almost worked last week on Dell D6000 and Dell UD 22 stations.

Except .... only one external monitor was usable. The other one was undetected. (works with pop 22 / Gnome)

**Comment by ace13131** [comment]
Having this issue on a hp zbook, attached are from the journctl -xb command for the logs

[last_100_logs.txt](https://github.com/user-attachments/files/21106267/last_100_logs.txt)

**Comment by Drakulix** [comment]
EDIT: ~ wrong thread ~

**Comment by ids1024** [comment]
The issue I see with a DisplayLink USB 3.0 device is a segfault in llvmpipe when trying to create a a window on the DisplayLink output (just clearing the screen to grey works fine).

[llvmpipe-evdi-crash.txt](https://github.com/user-attachments/files/21265844/llvmpipe-evdi-crash.txt)

Not sure why behavior would be different for others. In any cases, I don't see a change with https://github.com/pop-os/cosmic-comp/pull/1521 to this particular behavior (as expected, since it's not really related to that).

I don't know if this is really something wrong with the evdi driver used for DisplayLink... or with LLVMPipe. Presumably we should ideally do something like having `backend::kms::Device` use an `Option<DrmNode>` for `render_node`, set it to `None` if trying to initialize EGL gets a software renderer, and render with the primary GPU instead.

**Comment by ChadAPSheridan** [comment]
I've got it compiled and installed, my displaylink dock is for work, so I'll test it and grab logs on my lunch (~2 hours from the time of this post) then I'll update here.
-- EDIT --
Didn't think to update this until today as I saw the 'wrong thread' edit above. But I did test the PR suggested, and just for completeness' sake, errors in the logs regarding the displaylink issue are unchanged.

**Comment by ChadAPSheridan** [comment]
This is brilliant! I'm going to get everything downloaded and prepped so I can test when I'm back in the office Monday.

**Comment by zsilet** [comment]
@Drakulix thank you so much for fixing this. I've been waiting start of alpha to use my USB-HDMI dock again with my extra monitors. Got it running about a week ago with the latest Synaptics drivers and it's been working great.
