### ISSUE TITLE
Panic in `unwrap` in `tiny-skia-path`, in `CosmicMapped::split_render_elements`

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#432]
That's an interesting place to have a panic; I haven't seen that one before.

(Does something end up with a 0px size, maybe?)

```
Apr 18 19:26:30 Superficies cosmic-comp[33560]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tiny-skia-path-0.11.3/src/size.rs:88
                                                   0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                   1: log_panics::Config::install_panic_hook::{{closure}}
                                                   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                                                             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
                                                      std::panicking::rust_panic_with_hook
                                                             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
                                                   3: std::panicking::begin_panic_handler::{{closure}}
                                                             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:595:13
                                                   4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
                                                   5: rust_begin_unwind
                                                             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
                                                   6: core::panicking::panic_fmt
                                                             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
                                                   7: core::panicking::panic
                                                             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
                                                   8: tiny_skia::painter::<impl tiny_skia::pixmap::PixmapMut>::draw_pixmap
                                                   9: iced_tiny_skia::text::draw
                                                  10: iced_tiny_skia::backend::Backend::draw_primitive
                                                  11: iced_tiny_skia::backend::Backend::draw_primitive
                                                  12: iced_tiny_skia::backend::Backend::draw_primitive
                                                  13: iced_tiny_skia::backend::Backend::draw_primitive
                                                  14: iced_tiny_skia::backend::Backend::draw_primitive
                                                  15: iced_tiny_skia::backend::Backend::draw_primitive
                                                  16: iced_tiny_skia::backend::Backend::draw_primitive
                                                  17: iced_tiny_skia::backend::Backend::draw_primitive
                                                  18: iced_tiny_skia::backend::Backend::draw_primitive
                                                  19: iced_tiny_skia::backend::Backend::draw_primitive
                                                  20: iced_tiny_skia::backend::Backend::draw_primitive
                                                  21: iced_tiny_skia::backend::Backend::draw
                                                  22: cosmic_comp::shell::element::CosmicMapped::split_render_elements
                                                  23: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
                                                  24: cosmic_comp::shell::layout::tiling::TilingLayout::render
                                                  25: cosmic_comp::shell::workspace::Workspace::render
                                                  26: cosmic_comp::backend::render::workspace_elements
                                                  27: cosmic_comp::backend::kms::Surface::render_output
                                                  28: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                  29: calloop::loop_logic::EventLoop<Data>::run
                                                  30: cosmic_comp::main
                                                  31: std::sys_common::backtrace::__rust_begin_short_backtrace
                                                  32: main
                                                  33: __libc_start_call_main
                                                             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
                                                  34: __libc_start_main_impl
                                                             at ./csu/../csu/libc-start.c:360:3
                                                  35: _start
```

**Comment by talzion12** [comment]
I keep hitting this panic whenever I navigate to specific URLs in firefox ([example link](https://ksp.co.il/web/item/360932)). I'm not sure if what I'm experiencing is the same issue, but the panic is at the same location. Navigating to the same URL in chromium works fine.

It causes my cosmic environment to crash so it's pretty annoying.

Here is my stacktrace:
```
Feb 22 10:23:17 taco .cosmic-comp-wrapped[902227]: thread 'surface-DP-1' panicked at 'called `Option::unwrap()` on a `None` value': /build/cosmic-comp-1.0.0-vendor/tiny-skia-path-0.11.4/src/size.rs:88
                                                      0: log_panics::Config::install_panic_hook::{{closure}}
                                                      1: std::panicking::panic_with_hook
                                                      2: std::panicking::panic_handler::{{closure}}
                                                      3: std::sys::backtrace::__rust_end_short_backtrace
                                                      4: __rustc::rust_begin_unwind
                                                      5: core::panicking::panic_fmt
                                                      6: core::panicking::panic
                                                      7: core::option::unwrap_failed
                                                      8: tiny_skia::painter::<impl tiny_skia::pixmap::PixmapMut>::draw_pixmap
                                                      9: iced_tiny_skia::text::draw
                                                     10: iced_tiny_skia::Renderer::draw
                                                     11: cosmic_comp::shell::element::CosmicMapped::render_elements
                                                     12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
                                                     13: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::fold::flatten::{{closure}}
                                                     14: cosmic_comp::shell::layout::tiling::TilingLayout::render
                                                     15: cosmic_comp::backend::render::workspace_elements::{{closure}}
                                                     16: cosmic_comp::backend::render::workspace_elements
                                                     17: cosmic_comp::backend::render::output_elements
                                                     18: cosmic_comp::backend::kms::surface::SurfaceThreadState::redraw
                                                     19: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                     20: cosmic_comp::backend::kms::surface::surface_thread
                                                     21: std::sys::backtrace::__rust_begin_short_backtrace
                                                     22: core::ops::function::FnOnce::call_once{{vtable.shim}}
                                                     23: std::sys::thread::unix::Thread::new::thread_start
                                                     24: start_thread
                                                     25: __clone3
```

**Comment by modelmiser** [comment]
**Possible trigger: Firefox 0x0 display state after monitor power-cycle**

I hit this panic while scrolling YouTube Shorts in Firefox Nightly on COSMIC (~2.5 hours into the session):

```
thread 'surface-HDMI-A-1' panicked at 'called `Option::unwrap()` on a `None` value':
  tiny-skia-path/src/size.rs:88
```

The session had a prior monitor power-cycle (DPMS wake). Firefox has a known bug where `wl_output` destroy/recreate causes it to latch onto `0x0 @ scale 0.0` display dimensions permanently ([Mozilla bug 2018866](https://bugzilla.mozilla.org/show_bug.cgi?id=2018866)). In that state, GTK menu popups also fail to render — suggesting Firefox may be committing surfaces with degenerate geometry.

This aligns with @talzion12's report (also Firefox-triggered). The compositor should guard against zero-size surfaces in the render path regardless of what clients send.
