### ISSUE TITLE
Panic creating a stack

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#530]
This seems to happen consistently, starting with https://github.com/pop-os/cosmic-comp/commit/16cce7c97a2479878bf68e7c17db85137af720b1, when I right click the header bar and create a stack.

```
May 31 14:16:32 Superficies cosmic-comp[1757451]: thread 'main' panicked at 'assertion failed: old.id == new.id': /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/core/src/widget/tree.rs:188
                                                     0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                               at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.72/src/capture.rs:422:9
                                                     1: log_panics::Config::install_panic_hook::{{closure}}
                                                               at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
                                                     2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
                                                        std::panicking::rust_panic_with_hook
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
                                                     3: std::panicking::begin_panic_handler::{{closure}}
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:649:13
                                                     4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
                                                     5: rust_begin_unwind
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
                                                     6: core::panicking::panic_fmt
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
                                                     7: core::panicking::panic
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
                                                     8: iced_core::widget::tree::Tree::diff
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/core/src/widget/tree.rs:188:25
                                                     9: iced_core::widget::tree::Tree::diff_children::{{closure}}
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/core/src/widget/tree.rs:229:17
                                                    10: iced_core::widget::tree::Tree::diff_children_custom
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/core/src/widget/tree.rs:306:13
                                                    11: iced_core::widget::tree::Tree::diff_children
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/core/src/widget/tree.rs:224:9
                                                    12: <iced_widget::row::Row<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::diff
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/widget/src/row.rs:123:9
                                                    13: <iced_widget::container::Container<Message,Theme,Renderer> as iced_core::widget::Widget<Message,Theme,Renderer>>::diff
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/widget/src/container.rs:149:9
                                                    14: iced_core::widget::tree::Tree::diff
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/core/src/widget/tree.rs:211:13
                                                    15: iced_runtime::user_interface::UserInterface<Message,Theme,Renderer>::build
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/runtime/src/user_interface.rs:108:9
                                                    16: iced_runtime::program::state::build_user_interface
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/runtime/src/program/state.rs:290:26
                                                    17: iced_runtime::program::state::State<P>::update
                                                               at /home/ian/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/e1b78fd/iced/runtime/src/program/state.rs:105:34
                                                    18: cosmic_comp::utils::iced::IcedElementInternal<P>::update
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/utils/iced.rs:386:23
                                                    19: <cosmic_comp::utils::iced::IcedElement<P> as smithay::desktop::space::element::SpaceElement>::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/utils/iced.rs:838:9
                                                    20: <cosmic_comp::shell::element::stack::CosmicStack as smithay::desktop::space::element::SpaceElement>::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/element/stack.rs:1076:9
                                                    21: <cosmic_comp::shell::element::CosmicMappedInternal as smithay::desktop::space::element::SpaceElement>::refresh
                                                               at /home/ian/.cargo/git/checkouts/smithay-0141b1fcb9e16729/fb44b24/src/desktop/space/element/mod.rs:376:39
                                                    22: <cosmic_comp::shell::element::CosmicMapped as smithay::desktop::space::element::SpaceElement>::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/element/mod.rs:870:9
                                                    23: cosmic_comp::shell::layout::tiling::TilingLayout::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/layout/tiling/mod.rs:2310:13
                                                    24: cosmic_comp::shell::workspace::Workspace::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/workspace.rs:294:9
                                                    25: cosmic_comp::shell::WorkspaceSet::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/mod.rs:478:13
                                                    26: cosmic_comp::shell::Workspaces::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/mod.rs:885:13
                                                    27: cosmic_comp::shell::Shell::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/mod.rs:1641:9
                                                    28: cosmic_comp::shell::<impl cosmic_comp::state::Common>::refresh
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/shell/mod.rs:1102:9
                                                    29: cosmic_comp::main::{{closure}}
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/main.rs:146:9
                                                    30: calloop::loop_logic::EventLoop<Data>::run
                                                               at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.13.0/src/loop_logic.rs:597:13
                                                    31: cosmic_comp::main
                                                               at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/main.rs:120:5
                                                    32: core::ops::function::FnOnce::call_once
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
                                                    33: std::sys_common::backtrace::__rust_begin_short_backtrace
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
                                                    34: std::rt::lang_start::{{closure}}
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
                                                    35: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
                                                        std::panicking::try::do_call
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
                                                        std::panicking::try
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
                                                        std::panic::catch_unwind
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
                                                        std::rt::lang_start_internal::{{closure}}
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
                                                        std::panicking::try::do_call
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
                                                        std::panicking::try
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
                                                        std::panic::catch_unwind
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
                                                        std::rt::lang_start_internal
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
                                                    36: std::rt::lang_start
                                                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
                                                    37: main
                                                    38: __libc_start_call_main
                                                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
                                                    39: __libc_start_main_impl
                                                               at ./csu/../csu/libc-start.c:360:3
                                                    40: _start
```

**Comment by mmstick** [comment]
I think a fix was merged for the id containers yesterday, after this was merged.
