### ISSUE TITLE
cosmic-comp crashes when a specific display is connected

### ISSUE THREAD

**Issue by lavjamanxd** [pop-os/cosmic-comp#614]
I have a two monitor setup at home, one connected via DisplayPort (Viewsonic) and the other is connected via HDMI (no-name generic portable display named 'hgfrtee').

The crash happens when the portable display is connected. (no issues on GNOME)

What i tried so far:
- disconnecting the portable display -> works fine.
- disconnecting all the monitors, except the portable -> crash.
- connecting to the other hdmi port -> crash.
- disconnecting the portable monitor then launch cosmic session and then reconnect the portable one -> crash.
- connecting a different portable monitor -> works fine.
- tried to delete all the previous cosmic config files -> still crashing.

### drm_info output:
(/dev/dri/card1 -> connector 2 is the problematic display)
[drm_info.txt](https://github.com/user-attachments/files/16237297/drm_info.txt)

### Relevant logs from journalctl:
```
júl 15 16:59:48 sindragosa cosmic-session[8942]: Starting cosmic-session
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.446785Z  INFO cosmic_session: Starting cosmic-session
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.446845Z  INFO launch_pad: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
júl 15 16:59:48 sindragosa cosmic-session[8942]: starting process ' COSMIC_SESSION_SOCK=12 cosmic-comp '
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Failed to read config 'workspaces'
júl 15 16:59:48 sindragosa cosmic-comp[8982]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Key-Binding 'Period' only matched case insensitive for "period"
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Key-Binding 'Comma' only matched case insensitive for "comma"
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Key-Binding 'Period' only matched case insensitive for "period"
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Key-Binding 'Comma' only matched case insensitive for "comma"
júl 15 16:59:48 sindragosa cosmic-comp[8982]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Unable to become drm master, assuming unprivileged mode
júl 15 16:59:48 sindragosa cosmic-comp[8982]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0])': /home/beckeeh/.cache/yay/cosmic-comp-git/src/cosmic-comp/vendor/wayland-serv
er/src/lib.rs:123
                                                  0: <unknown>
                                                  1: <unknown>
                                                  2: <unknown>
                                                  3: <unknown>
                                                  4: <unknown>
                                                  5: <unknown>
                                                  6: <unknown>
                                                  7: <unknown>
                                                  8: <unknown>
                                                  9: <unknown>
                                                 10: <unknown>
                                                 11: <unknown>
                                                 12: <unknown>
                                                 13: <unknown>
                                                 14: <unknown>
                                                 15: <unknown>
                                                 16: <unknown>
                                                 17: <unknown>
                                                 18: __libc_start_main
                                                 19: <unknown>
júl 15 16:59:48 sindragosa cosmic-comp[8982]: thread 'surface-HDMI-A-1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /home/beckeeh/.cache/yay/cosmic-comp-git/src/cosmic-comp/vendo
r/smithay/src/output.rs:527
                                                  0: <unknown>
                                                  1: <unknown>
                                                  2: <unknown>
                                                  3: <unknown>
                                                  4: <unknown>
                                                  5: <unknown>
                                                  6: <unknown>
                                                  7: <unknown>
                                                  8: <unknown>
                                                  9: <unknown>
                                                 10: <unknown>
                                                 11: <unknown>
                                                 12: <unknown>
                                                 13: <unknown>
                                                 14: <unknown>
                                                 15: <unknown>
                                                 16: <unknown>
                                                 17: <unknown>
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Failed to submit rendering: Failed to submit result for display
                                               
                                               Caused by:
                                                   0: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                   1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                   2: Permission denied (os error 13)
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Failed to submit rendering: Failed to submit result for display
                                               
                                               Caused by:
                                                   0: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                   1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                   2: Permission denied (os error 13)
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Unable to clear state: DRM access error: Failed to commit on clear_state on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
júl 15 16:59:48 sindragosa cosmic-comp[8982]: Failed to restore previous state. Error: Permission denied (os error 13)
júl 15 16:59:48 sindragosa cosmic-session[8942]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.765719Z ERROR launch_pad: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.765736Z ERROR cosmic_session::comp: cosmic-comp exited with error code 101
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.765743Z  INFO launch_pad: draining stdin receiver before restarting process
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.765758Z  INFO launch_pad: sleeping for 2ms before restarting process cosmic-comp (restart 0)
júl 15 16:59:48 sindragosa cosmic-session[8942]: cosmic-comp exited with error code 101
júl 15 16:59:48 sindragosa cosmic-session[8942]: draining stdin receiver before restarting process
júl 15 16:59:48 sindragosa cosmic-session[8942]: sleeping for 2ms before restarting process cosmic-comp (restart 0)
júl 15 16:59:48 sindragosa cosmic-session[8942]: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.769382Z  INFO launch_pad: restarted process ' COSMIC_SESSION_SOCK=12 cosmic-comp ', now at 1 restarts
júl 15 16:59:48 sindragosa /usr/lib/gdm-wayland-session[8942]: 2024-07-15T14:59:48.769422Z  INFO launch_pad: process 'ProcessKey(1v1)' cancelled
júl 15 16:59:48 sindragosa cosmic-session[8942]: process 'ProcessKey(1v1)' cancelled
```

**Comment by lavjamanxd** [comment]
Sadly no, still crashing

Built a cosmic-comp with the fix applied (got stacktrace and symbols this time)

```
júl 17 19:53:08 sindragosa cosmic-comp[555510]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0])': /mnt/storage/repo/aur/cosmic-comp-git/src/cosmic-comp/vendor/wayland-server/src/lib.rs:123
                                                    0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                    1: log_panics::Config::install_panic_hook::{{closure}}
                                                    2: std::panicking::rust_panic_with_hook
                                                    3: std::panicking::begin_panic_handler::{{closure}}
                                                    4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                    5: rust_begin_unwind
                                                    6: core::panicking::panic_fmt
                                                    7: core::result::unwrap_failed
                                                    8: <wayland_server::protocol::wl_output::WlOutput as wayland_server::Resource>::send_event
                                                    9: smithay::wayland::output::<impl smithay::output::Inner>::send_geometry_to
                                                   10: <wayland_server::global::GlobalData<I,U,D> as wayland_backend::rs::server::GlobalHandler<D>>::bind
                                                   11: wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_events_for
                                                   12: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                   13: calloop::loop_logic::EventLoop<Data>::run
                                                   14: cosmic_comp::main
                                                   15: std::sys_common::backtrace::__rust_begin_short_backtrace
                                                   16: main
                                                   17: <unknown>
                                                   18: __libc_start_main
                                                   19: _start
júl 17 19:53:08 sindragosa cosmic-comp[555510]: thread 'surface-HDMI-A-1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /mnt/storage/repo/aur/cosmic-comp-git/src/cosmic-comp/vendor/smithay/src/output.rs:332
                                                    0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                    1: log_panics::Config::install_panic_hook::{{closure}}
                                                    2: std::panicking::rust_panic_with_hook
                                                    3: std::panicking::begin_panic_handler::{{closure}}
                                                    4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                    5: rust_begin_unwind
                                                    6: core::panicking::panic_fmt
                                                    7: core::result::unwrap_failed
                                                    8: smithay::output::Output::current_location
                                                    9: cosmic_comp::backend::render::workspace_elements
                                                   10: cosmic_comp::backend::kms::surface::SurfaceThreadState::redraw
                                                   11: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                   12: cosmic_comp::backend::kms::surface::surface_thread
                                                   13: std::sys_common::backtrace::__rust_begin_short_backtrace
                                                   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
                                                   15: std::sys::pal::unix::thread::Thread::new::thread_start
                                                   16: <unknown>
                                                   17: <unknown>

```

Let me know what kind of logs do you need for easier debugging.

**Comment by lavjamanxd** [comment]
Made a debug build with file/linenumbers

```
júl 17 20:30:56 sindragosa cosmic-comp[593034]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0])': /mnt/storage/repo/aur/cosmic-comp-git/src/cosmic-comp/vendor/wayland-server/src/lib.rs:123
                                                    0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/backtrace/src/capture.rs:422:9
                                                    1: log_panics::Config::install_panic_hook::{{closure}}
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/log-panics/src/lib.rs:115:29
                                                    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/alloc/src/boxed.rs:2036:9
                                                       std::panicking::rust_panic_with_hook
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:799:13
                                                    3: std::panicking::begin_panic_handler::{{closure}}
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:664:13
                                                    4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/sys_common/backtrace.rs:171:18
                                                    5: rust_begin_unwind
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:652:5
                                                    6: core::panicking::panic_fmt
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/panicking.rs:72:14
                                                    7: core::result::unwrap_failed
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/result.rs:1654:5
                                                    8: core::result::Result<T,E>::unwrap
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/result.rs:1077:23
                                                       <wayland_server::protocol::wl_output::WlOutput as wayland_server::Resource>::write_event
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-server/src/lib.rs:123:5
                                                       wayland_server::display::DisplayHandle::send_event
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-server/src/display.rs:180:19
                                                       <wayland_server::protocol::wl_output::WlOutput as wayland_server::Resource>::send_event
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-server/src/lib.rs:123:5
                                                    9: wayland_server::protocol::wl_output::WlOutput::geometry
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-server/src/lib.rs:123:5
                                                       smithay::wayland::output::<impl smithay::output::Inner>::send_geometry_to
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/smithay/src/wayland/output/mod.rs:137:9
                                                   10: smithay::wayland::output::handlers::<impl wayland_server::global::GlobalDispatch<wayland_server::protocol::wl_output::WlOutput,smithay::wayland::output::WlOutputData,D> for smithay::wayland::output::OutputManagerState>::bind
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/smithay/src/wayland/output/handlers.rs:56:9
                                                       cosmic_comp::wayland::handlers::output::<impl wayland_server::global::GlobalDispatch<wayland_server::protocol::wl_output::WlOutput,smithay::wayland::output::WlOutputData> for cosmic_comp::state::State>::bind
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-server/src/global.rs:146:17
                                                       <wayland_server::global::GlobalData<I,U,D> as wayland_backend::rs::server::GlobalHandler<D>>::bind
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-server/src/global.rs:42:9
                                                   11: wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_events_for
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-backend/src/rs/server_impl/common_poll.rs:308:38
                                                       wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_all_clients
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-backend/src/rs/server_impl/common_poll.rs:97:36
                                                   12: wayland_backend::rs::server::Backend<D>::dispatch_all_clients
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-backend/src/rs/../server_api.rs:579:9
                                                       wayland_server::display::Display<State>::dispatch_clients
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/wayland-server/src/display.rs:59:22
                                                       cosmic_comp::init_wayland_display::{{closure}}
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/src/main.rs:213:50
                                                       <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/sources/mod.rs:327:61
                                                       <calloop::sources::generic::Generic<F,E> as calloop::sources::EventSource>::process_events
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/sources/generic.rs:290:9
                                                       <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/sources/mod.rs:326:9
                                                   13: calloop::loop_logic::EventLoop<Data>::dispatch_events
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/loop_logic.rs:445:31
                                                       calloop::loop_logic::EventLoop<Data>::dispatch
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/loop_logic.rs:559:9
                                                       calloop::loop_logic::EventLoop<Data>::run
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/loop_logic.rs:596:13
                                                   14: cosmic_comp::main
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/src/main.rs:115:5
                                                   15: core::ops::function::FnOnce::call_once
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/ops/function.rs:250:5
                                                       std::sys_common::backtrace::__rust_begin_short_backtrace
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/sys_common/backtrace.rs:155:18
                                                   16: main
                                                   17: <unknown>
                                                   18: __libc_start_main
                                                   19: _start
júl 17 20:30:56 sindragosa cosmic-comp[593034]: thread 'surface-HDMI-A-1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /mnt/storage/repo/aur/cosmic-comp-git/src/cosmic-comp/vendor/smithay/src/output.rs:527
                                                    0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/backtrace/src/capture.rs:422:9
                                                    1: log_panics::Config::install_panic_hook::{{closure}}
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/log-panics/src/lib.rs:115:29
                                                    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/alloc/src/boxed.rs:2036:9
                                                       std::panicking::rust_panic_with_hook
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:799:13
                                                    3: std::panicking::begin_panic_handler::{{closure}}
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:664:13
                                                    4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/sys_common/backtrace.rs:171:18
                                                    5: rust_begin_unwind
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:652:5
                                                    6: core::panicking::panic_fmt
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/panicking.rs:72:14
                                                    7: core::result::unwrap_failed
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/result.rs:1654:5
                                                    8: core::result::Result<T,E>::unwrap
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/result.rs:1077:23
                                                       smithay::output::<impl core::convert::TryFrom<&smithay::output::OutputModeSource> for (smithay::utils::geometry::Size<i32,smithay::utils::geometry::Physical>,smithay::utils::geometry::Scale<f64>,smithay::utils::geometry::Transform)>::try_from
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/smithay/src/output.rs:527:29
                                                    9: <T as core::convert::TryInto<U>>::try_into
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/convert/mod.rs:798:9
                                                       smithay::backend::renderer::damage::OutputDamageTracker::render_output_internal
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/smithay/src/backend/renderer/damage/mod.rs:794:13
                                                   10: smithay::backend::renderer::damage::OutputDamageTracker::render_output_with
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/smithay/src/backend/renderer/damage/mod.rs:431:9
                                                       smithay::backend::drm::compositor::DrmCompositor<A,F,U,G>::render_frame
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/smithay/src/backend/drm/compositor/mod.rs:2446:17
                                                   11: cosmic_comp::backend::kms::surface::SurfaceThreadState::redraw
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/src/backend/kms/surface/mod.rs:1054:13
                                                   12: cosmic_comp::backend::kms::surface::SurfaceThreadState::queue_redraw::{{closure}}
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/src/backend/kms/surface/mod.rs:800:35
                                                       <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/sources/mod.rs:327:61
                                                       <calloop::sources::timer::Timer as calloop::sources::EventSource>::process_events
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/sources/timer.rs:122:38
                                                       <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/sources/mod.rs:326:9
                                                   13: calloop::loop_logic::EventLoop<Data>::dispatch_events
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/loop_logic.rs:445:31
                                                       calloop::loop_logic::EventLoop<Data>::dispatch
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/loop_logic.rs:559:9
                                                       calloop::loop_logic::EventLoop<Data>::run
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/vendor/calloop/src/loop_logic.rs:596:13
                                                       cosmic_comp::backend::kms::surface::surface_thread
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/src/backend/kms/surface/mod.rs:545:5
                                                       cosmic_comp::backend::kms::surface::Surface::new::{{closure}}
                                                              at /usr/src/debug/cosmic-comp-git/cosmic-comp/src/backend/kms/surface/mod.rs:271:35
                                                       std::sys_common::backtrace::__rust_begin_short_backtrace
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/sys_common/backtrace.rs:155:18
                                                   14: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/thread/mod.rs:542:17
                                                       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/panic/unwind_safe.rs:272:9
                                                       std::panicking::try::do_call
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:559:40
                                                       std::panicking::try
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panicking.rs:523:19
                                                       std::panic::catch_unwind
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/panic.rs:149:14
                                                       std::thread::Builder::spawn_unchecked_::{{closure}}
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/thread/mod.rs:541:30
                                                       core::ops::function::FnOnce::call_once{{vtable.shim}}
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/core/src/ops/function.rs:250:5
                                                   15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/alloc/src/boxed.rs:2022:9
                                                       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/alloc/src/boxed.rs:2022:9
                                                       std::sys::pal::unix::thread::Thread::new::thread_start
                                                              at /usr/src/debug/rust/rustc-1.79.0-src/library/std/src/sys/pal/unix/thread.rs:108:17
                                                   16: <unknown>
                                                   17: <unknown>
```

**Comment by Drakulix** [comment]
Oh fun, this looks like the model-string we get from the EDID might contain a null-byte, which we can't send to wayland-clients since that is illegal and so wayland-rs right fully panics.
I added another commit to said branch, which should filter the name, does that fix it? (Also thanks for that second log, that is much more helpful!)

**Comment by lavjamanxd** [comment]
Yes, it works with that fix 🥳 

I was able to dump edid for that display (it has lot of weird zeroes at the end, compared to my other monitor)

```
 ~ xxd /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/drm/card1/card1-HDMI-A-1/edid
00000000: 00ff ffff ffff ff00 4a8b 2019 8010 2019  ........J. ... .
00000010: 0f21 0103 8100 0078 ecde 58a3 544c 9926  .!.....x..X.TL.&
00000020: 0f47 4aaf cf00 d1c0 b300 a9c0 d1cf 9500  .GJ.............
00000030: 8180 6140 4540 023a 8018 7138 2d40 582c  ..a@E@.:..q8-@X,
00000040: 4500 ba89 2100 001e ae60 8018 7138 2d40  E...!....`..q8-@
00000050: 3020 3500 ba89 2100 001e 0000 00fd 0030  0 5...!........0
00000060: 651e a01e 000a 2020 2020 2020 0000 00fc  e.....      ....
00000070: 0000 0a20 2020 2020 2020 2020 2020 0120  ...           .
00000080: 0203 32f2 4f04 0510 1314 1f20 4022 c048  ..2.O...... @".H
00000090: 494c 464d e200 eae3 05c0 0023 097f 0783  ILFM.......#....
000000a0: 0100 0067 030c 0010 0038 3ce6 0605 0169  ...g.....8<....i
000000b0: 694f 9745 80a0 7038 3e40 3020 2500 58c3  iO.E..p8>@0 %.X.
000000c0: 1000 001e 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000f0: 0000 0000 0000 0000 0000 0000 0000 00e0  ................
```

**Comment by Drakulix** [comment]
Great! merged the fix. :)
