### ISSUE TITLE
Crashes running `simple_window` example from `sctk`

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#66]
```
Jan 31 21:39:05.626 ERRO thread 'main' panicked at 'cast_slice_mut>TargetAlignmentGreaterAndInputNotAligned': /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.13.0/src/internal.rs:32
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.67/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.1.0/src/lib.rs:115:29
   2: std::panicking::rust_panic_with_hook
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   7: bytemuck::internal::something_went_wrong
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.13.0/src/internal.rs:32:3
   8: bytemuck::internal::cast_slice_mut
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.13.0/src/internal.rs:249:15
   9: bytemuck::cast_slice_mut
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.13.0/src/lib.rs:300:12
  10: <cosmic_comp::utils::iced::IcedElement<P> as smithay::backend::renderer::element::AsRenderElements<R>>::render_elements::{{closure}}
             at src/utils/iced.rs:569:29
  11: smithay::backend::renderer::element::memory::RenderContext::draw
             at /home/ian/.cargo/git/checkouts/smithay-1fd533335f33e976/3437fe1/src/backend/renderer/element/memory.rs:427:27
  12: <cosmic_comp::utils::iced::IcedElement<P> as smithay::backend::renderer::element::AsRenderElements<R>>::render_elements
             at src/utils/iced.rs:563:17
  13: <cosmic_comp::shell::element::window::CosmicWindow as smithay::backend::renderer::element::AsRenderElements<R>>::render_elements
             at src/shell/element/window.rs:556:29
  14: <cosmic_comp::shell::element::CosmicMapped as smithay::backend::renderer::element::AsRenderElements<R>>::render_elements
             at src/shell/element/mod.rs:1037:33
  15: smithay::desktop::space::Space<E>::render_elements_for_region::{{closure}}
             at /home/ian/.cargo/git/checkouts/smithay-1fd533335f33e976/3437fe1/src/desktop/space/mod.rs:400:17
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:306:13
  17: core::option::Option<T>::map
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:929:29
  18: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/map.rs:103:9
  19: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/fuse.rs:337:9
  20: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/fuse.rs:43:9
      <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/flatten.rs:474:19
  21: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/adapters/flatten.rs:51:9
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/vec/spec_from_iter.rs:33:9
  24: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/vec/mod.rs:2649:9
  25: core::iter::traits::iterator::Iterator::collect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/iter/traits/iterator.rs:1836:9
  26: smithay::desktop::space::Space<E>::render_elements_for_region
             at /home/ian/.cargo/git/checkouts/smithay-1fd533335f33e976/3437fe1/src/desktop/space/mod.rs:391:9
  27: cosmic_comp::shell::layout::floating::FloatingLayout::render_output
             at src/shell/layout/floating/mod.rs:361:12
  28: cosmic_comp::shell::workspace::Workspace::render_output
             at src/shell/workspace.rs:523:17
  29: cosmic_comp::backend::render::render_workspace
             at src/backend/render/mod.rs:262:9
  30: cosmic_comp::backend::render::render_output
             at src/backend/render/mod.rs:160:18
  31: cosmic_comp::backend::x11::Surface::render_output
             at src/backend/x11.rs:200:15
  32: cosmic_comp::backend::x11::X11State::add_window::{{closure}}
             at src/backend/x11.rs:107:25
  33: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/sources/mod.rs:306:61
  34: <calloop::sources::ping::eventfd::PingSource as calloop::sources::EventSource>::process_events::{{closure}}
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/sources/ping/eventfd.rs:133:21
  35: <calloop::sources::generic::Generic<F,E> as calloop::sources::EventSource>::process_events
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/sources/generic.rs:121:9
  36: <calloop::sources::ping::eventfd::PingSource as calloop::sources::EventSource>::process_events
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/sources/ping/eventfd.rs:122:9
  37: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/sources/mod.rs:305:9
  38: calloop::loop_logic::EventLoop<Data>::dispatch_events
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/loop_logic.rs:300:31
  39: calloop::loop_logic::EventLoop<Data>::run
             at /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/loop_logic.rs:454:13
  40: cosmic_comp::main
             at src/main.rs:56:5
  41: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  43: std::rt::lang_start::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
  44: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
      std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  45: std::rt::lang_start
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:165:17
  46: main
  47: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  48: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  49: _start

```

**Comment by Drakulix** [comment]
Should be fixed by https://github.com/pop-os/cosmic-comp/commit/649b9008336c970dbea5042433ea7d083fef10ee
