### ISSUE TITLE
NVIDIA desktop suspend/resume failure

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-comp#694]
On a Thelio Mira B4 with an RTX 4060 Ti, the system suspends, but hangs at a black screen on resume.

Log file: [out.txt](https://github.com/user-attachments/files/16533501/out.txt)

Outtake of note:

```
Aug 07 19:50:54 pop-os cosmic-comp[2004]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Aug 07 19:50:54 pop-os cosmic-comp[2004]: thread 'surface-HDMI-A-3' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:726
                                             0: <unknown>
                                             1: <unknown>
                                             2: <unknown>
                                             3: <unknown>
                                             4: <unknown>
                                             5: <unknown>
                                             6: <unknown>
                                             7: <unknown>
                                             8: <unknown>
                                             9: <unknown>
                                            10: <unknown>
                                            11: <unknown>
                                            12: <unknown>
                                            13: <unknown>
                                            14: <unknown>
                                            15: <unknown>
```

**Comment by StayBlue** [comment]
I believe this is an issue with Nvidia itself, not Cosmic. You can see the forum post I made on the [Nvidia forum](https://forums.developer.nvidia.com/t/black-screen-after-pc-wakes-up-from-suspend/304023) if you would like, although it doesn't provide any logs. Other people on the forum have reported similar issues with other desktop environments as well.

**Comment by TigerGorilla2** [comment]
I have the same issue (surface-<monitor> threads panicking) with a GTX 1050 Ti on  fedora 42, nvidia driver 580.82.09, and cosmic-comp-1.0.0~beta.1-1.fc42.src.rpm. It happens when the monitor is plugged into the gpu or plugged into the motherboard (using Ryzen 5600G) with the nvidia drivers loaded. It does not happen when i `rmmod` the nvidia driver. Using the patches from PR #699 ([a rebased version onto beta1.1](https://github.com/TigerGorilla2/cosmic-comp-fix-resume/tree/fix-resume)) I dont have resume issues anymore.

**Comment by jacobgkau** [comment]
A Thelio Mira B4 with a 4060 Ti in our lab is now suspending/resuming successfully, even without #699. (An RTX 5050 and a GTX 1030 are also suspending/resuming successfully in that Mira B4.) So while we can still move forward with #699 if desired, we'll need to simply regression test rather than being able to confirm it fixes the specific issue I originally reported.

**Comment by mati865** [comment]
Happened to me with RTX 4080 recently after waking from sleep:
```
paź 24 15:05:02 cachyos kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeout on head 0
paź 24 15:05:05 cachyos kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeout on head 0
paź 24 15:05:05 cachyos cosmic-comp[1513]: Failed to destroy old mode property blob: No such file or directory (os error 2)
paź 24 15:05:05 cachyos root[194972]: ACPI group/action undefined: jack/lineout / LINEOUT
paź 24 15:05:05 cachyos root[194974]: ACPI group/action undefined: jack/videoout / VIDEOOUT
paź 24 15:05:05 cachyos cosmic-comp[1513]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
paź 24 15:05:05 cachyos cosmic-comp[1513]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
paź 24 15:05:05 cachyos cosmic-comp[1513]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
paź 24 15:05:05 cachyos cosmic-comp[1513]: thread 'surface-DP-3' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:864
                                               0: <unknown>
...
```
This has happened only a 2nd time within few months, so I cannot easily reproduce it.

**Comment by TigerGorilla2** [comment]
Using beta3 (cosmic-comp-1.0.0~beta.3-1.fc43.src.rpm) and beta4 (manually built) I can still reproduce this issue.

I was even able to reproduce it by suspending & resuming ~5 times on the login screen before logging in (only tested with beta3).
I felt like changing audio output to HDMI/DP monitor had an influence, but it probably just takes a few suspend & resume cycles trigger.

I am now running a [patched version of beta-4](https://github.com/TigerGorilla2/cosmic-comp-fix-resume/tree/beta-4-with-fix) without issues so far.

Example output of <code>journalctl -t cosmic-comp.beta-4</code>
```
[...]
Nov 03 18:13:10 david-pc cosmic-comp.beta-4[2126]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:13:10 david-pc cosmic-comp.beta-4[2126]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Nov 03 18:13:10 david-pc cosmic-comp.beta-4[2126]: Failed to submit rendering: Failed to submit result for display
                                                   
                                                   Caused by:
                                                       0: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Device or resource busy (os error 16))
                                                       1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Device or resource busy (os error 16))
                                                       2: Device or resource busy (os error 16)
Nov 03 18:13:10 david-pc cosmic-comp.beta-4[2126]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:13:10 david-pc cosmic-comp.beta-4[2126]: thread 'surface-DP-1' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:859
                                                      0: log_panics::Config::install_panic_hook::{{closure}}
                                                      1: std::panicking::rust_panic_with_hook
                                                      2: std::panicking::begin_panic_handler::{{closure}}
                                                      3: std::sys::backtrace::__rust_end_short_backtrace
                                                      4: __rustc::rust_begin_unwind
                                                      5: core::panicking::panic_fmt
                                                      6: core::panicking::panic
                                                      7: cosmic_comp::backend::kms::surface::SurfaceThreadState::on_vblank
                                                      8: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
                                                      9: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                     10: std::sys::backtrace::__rust_begin_short_backtrace
                                                     11: core::ops::function::FnOnce::call_once{{vtable.shim}}
                                                     12: std::sys::pal::unix::thread::Thread::new::thread_start
                                                     13: start_thread
                                                     14: __clone3
Nov 03 18:13:22 david-pc cosmic-comp.beta-4[2126]: Error while handling udev event.
Nov 03 18:13:22 david-pc cosmic-comp.beta-4[2126]: Error while handling udev event.
Nov 03 18:13:30 david-pc cosmic-comp.beta-4[2126]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:13:30 david-pc cosmic-comp.beta-4[2126]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:14:16 david-pc cosmic-comp.beta-4[2126]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:14:16 david-pc cosmic-comp.beta-4[2126]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:14:16 david-pc cosmic-comp.beta-4[2126]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': /root/.cargo/git/checkouts/smithay-312425d48e59d8c8/eb45814/src/backend/drm/output.rs:842
                                                      0: log_panics::Config::install_panic_hook::{{closure}}
                                                      1: std::panicking::rust_panic_with_hook
                                                      2: std::panicking::begin_panic_handler::{{closure}}
                                                      3: std::sys::backtrace::__rust_end_short_backtrace
                                                      4: __rustc::rust_begin_unwind
                                                      5: core::panicking::panic_fmt
                                                      6: core::panicking::panic
                                                      7: core::option::unwrap_failed
                                                      8: smithay::backend::drm::output::use_mode_internal
                                                      9: cosmic_comp::backend::kms::KmsGuard::apply_config_for_outputs
                                                     10: cosmic_comp::state::LockedBackend::apply_config_for_outputs
                                                     11: cosmic_comp::config::Config::read_outputs
                                                     12: cosmic_comp::backend::kms::device::<impl cosmic_comp::state::State>::refresh_output_config
                                                     13: <core::option::Option<F> as calloop::sources::IdleDispatcher<Data>>::dispatch
                                                     14: calloop::loop_logic::EventLoop<Data>::run
                                                     15: cosmic_comp::main
                                                     16: std::sys::backtrace::__rust_begin_short_backtrace
                                                     17: main
                                                     18: __libc_start_call_main
                                                     19: __libc_start_main_alias_1
                                                     20: _start
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:18 david-pc cosmic-comp.beta-4[5493]: 
Nov 03 18:14:19 david-pc cosmic-comp.beta-4[5493]: Unable to become drm master, assuming unprivileged mode
Nov 03 18:14:19 david-pc cosmic-comp.beta-4[5493]: Unable to become drm master, assuming unprivileged mode
Nov 03 18:16:26 david-pc cosmic-comp.beta-4[5493]: Client bug: Unable to re-configure repositioned popup.
Nov 03 18:16:36 david-pc cosmic-comp.beta-4[5493]: Failed to submit rendering: Failed to submit result for display
                                                   
                                                   Caused by:
                                                       0: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                       1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                       2: Permission denied (os error 13)
Nov 03 18:16:44 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:16:44 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:16:44 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:16:44 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:16:44 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:16:44 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:16:45 david-pc cosmic-comp.beta-4[5493]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Nov 03 18:16:45 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:16:56 david-pc cosmic-comp.beta-4[5493]: Failed to submit rendering: Failed to submit result for display
                                                   
                                                   Caused by:
                                                       0: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                       1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Permission denied (os error 13))
                                                       2: Permission denied (os error 13)
Nov 03 18:17:06 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:17:06 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
[...]
Nov 03 18:19:15 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:19:15 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:19:15 david-pc cosmic-comp.beta-4[5493]: Failed to destroy old mode property blob: No such file or directory (os error 2)
Nov 03 18:19:15 david-pc cosmic-comp.beta-4[5493]: Failed to submit rendering: Failed to submit result for display
                                                   
                                                   Caused by:
                                                       0: The underlying drm surface encountered an error: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Device or resource busy (os error 16))
                                                       1: DRM access error: Page flip commit failed on device `Some("/dev/dri/card1")` (Device or resource busy (os error 16))
                                                       2: Device or resource busy (os error 16)
Nov 03 18:19:15 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:19:16 david-pc cosmic-comp.beta-4[5493]: thread 'surface-DP-1' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:859
                                                      0: log_panics::Config::install_panic_hook::{{closure}}
                                                      1: std::panicking::rust_panic_with_hook
                                                      2: std::panicking::begin_panic_handler::{{closure}}
                                                      3: std::sys::backtrace::__rust_end_short_backtrace
                                                      4: __rustc::rust_begin_unwind
                                                      5: core::panicking::panic_fmt
                                                      6: core::panicking::panic
                                                      7: cosmic_comp::backend::kms::surface::SurfaceThreadState::on_vblank
                                                      8: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
                                                      9: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                     10: std::sys::backtrace::__rust_begin_short_backtrace
                                                     11: core::ops::function::FnOnce::call_once{{vtable.shim}}
                                                     12: std::sys::pal::unix::thread::Thread::new::thread_start
                                                     13: start_thread
                                                     14: __clone3
Nov 03 18:19:24 david-pc cosmic-comp.beta-4[5493]: Error while handling udev event.
Nov 03 18:19:24 david-pc cosmic-comp.beta-4[5493]: Error while handling udev event.
Nov 03 18:19:27 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:19:27 david-pc cosmic-comp.beta-4[5493]: Failed to set xwayland primary output: The provided output wasn't known to Xwayland
Nov 03 18:19:27 david-pc cosmic-comp.beta-4[5493]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': /root/.cargo/git/checkouts/smithay-312425d48e59d8c8/eb45814/src/backend/drm/output.rs:842
                                                      0: log_panics::Config::install_panic_hook::{{closure}}
                                                      1: std::panicking::rust_panic_with_hook
                                                      2: std::panicking::begin_panic_handler::{{closure}}
                                                      3: std::sys::backtrace::__rust_end_short_backtrace
                                                      4: __rustc::rust_begin_unwind
                                                      5: core::panicking::panic_fmt
                                                      6: core::panicking::panic
                                                      7: core::option::unwrap_failed
                                                      8: smithay::backend::drm::output::use_mode_internal
                                                      9: cosmic_comp::backend::kms::KmsGuard::apply_config_for_outputs
                                                     10: cosmic_comp::state::LockedBackend::apply_config_for_outputs
                                                     11: cosmic_comp::config::Config::read_outputs
                                                     12: cosmic_comp::backend::kms::device::<impl cosmic_comp::state::State>::refresh_output_config
                                                     13: <core::option::Option<F> as calloop::sources::IdleDispatcher<Data>>::dispatch
                                                     14: calloop::loop_logic::EventLoop<Data>::run
                                                     15: cosmic_comp::main
                                                     16: std::sys::backtrace::__rust_begin_short_backtrace
                                                     17: main
                                                     18: __libc_start_call_main
                                                     19: __libc_start_main_alias_1
                                                     20: _start
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: 
Nov 03 18:19:29 david-pc cosmic-comp.beta-4[10544]: Unable to become drm master, assuming unprivileged mode
Nov 03 18:19:30 david-pc cosmic-comp.beta-4[10544]: Unable to become drm master, assuming unprivileged mode
Nov 03 18:21:40 david-pc cosmic-comp.beta-4[10544]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 999 > 997)
Nov 03 18:21:40 david-pc cosmic-comp.beta-4[10544]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 774 > 772)
Nov 03 18:22:12 david-pc cosmic-comp.beta-4[10544]: Failed to force redraw for corner radius change.
Nov 03 18:23:05 david-pc cosmic-comp.beta-4[10544]: Client bug: Unable to re-configure repositioned popup.
Nov 03 18:23:20 david-pc cosmic-comp.beta-4[10544]: Error reading from session socket
```

**Comment by jacobgkau** [comment]
@TigerGorilla2 Could you try installing the branch from https://github.com/pop-os/cosmic-comp/pull/699 and confirm if it also fixes the issue like your custom branch does? Some of the changes that you pulled from there have been pared back, so I just want to confirm it's still effective to fix the issue, since I can no longer recreate it myself.

**Comment by jacobgkau** [comment]
I'm going to go ahead and mark this as fixed by https://github.com/pop-os/cosmic-comp/pull/699. It would still be great to hear back from @TigerGorilla2 or any other users affected with this specific log pattern to confirm.

**Comment by TigerGorilla2** [comment]
I have compiled master with the merged changes (6288789) and can confirm that it fixes the issue :)

My Email went down on the 26th, so I missed the activity here and only noticed this weekend...

**Comment by andreygal** [comment]
Same issue with COSMIC as above.
RTX 5090, multi-monitor DP
Unable to clear state: DRM access error... Permission denied right before suspend
The flip event timeouts on resume
nvidia-suspend.service has no ordering dependency on cosmic-comp releasing DRM

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/25666544/nvidia-bug-report.log.gz)
