### ISSUE TITLE
Turning off a monitor closes all of the windows open on that monitor

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-comp#837]
If you turn off a monitor with windows open all of the windows on the monitor are closed, they should probably just be moved over to another one of the monitors that are turned on. But if you have a single monitor setup this is not possible, so maybe some other behavior is required

Replication:
1. Open a bunch of windows on a monitor
2. Turn off the monitor
3. Turn on the monitor
4. Windows are closed

**Comment by 10leej** [comment]
I'm curious if this is because of a lack of a headless mode?

Also Brodie these are clients not windows.

**Comment by Quackdoc** [comment]
Which applications? I just tested with cosmic-files and this seems to be the current behavior at least on my dual monitor setup.

**Comment by BrodieRobertson** [comment]
Upon further testing the issue is a bit weirder than the applications just closing, when you turn off the monitor and then power it back on all the windows do actually remain open but you're moved to a workspace where none of the windows are present (I got confused a little when streaming), the windows across every workspace also have there positions reset to the origin point.

This seems to occur regardless of the toolkit

https://github.com/user-attachments/assets/98e30bcd-f862-4867-8e23-eadee5762749

**Comment by Dahipppo1555** [comment]
@BrodieRobertson still alpha, not even alpha2.

but i am sure it will be ironed out. 🚀

**Comment by pears0** [comment]
I have the same issue. In my case, they definitely don't move to a different workspace, they are full on closed. It appears that turning the monitor off kills the cosmic-comp process and it starts up again when the monitor is turned back on. Obviously this kills off all the child processes. This is likely an issue because of headless mode not being available if that's the case.

**Comment by JoaoDelille** [comment]
yep same here, everything gets closed if I turn off my monitor, they're not moved to another workspace or anything, they just close and don't come back, which is really annoying because it means you can't leave turn off the display while leaving something running on the PC and walking away. Right now this is one of the more annoying issues with cosmic, imo.

**Comment by jokeyrhyme** [comment]
Yep, sounds like https://github.com/pop-os/cosmic-comp/issues/679

**Comment by pullasuti** [comment]
Ouch, just noticed this on a system I leave on at nights. In my case, at least the terminal (if open) does stay running somewhere in the background even though cosmic-comp goes down. I had a long running process going on in a cosmic-term, and both the terminal process and the child can be found and reattached to with reptyr (thank goodness :relieved: )

Also noticed I can't use or launch the visual workspace manager, but can switch with keyboard shortcuts (no windows present from previous session). 

Haven't noticed this with my laptop, however. I supposed it manages to wake the display before the system has resumed from sleep.

**Comment by foggerty** [comment]
I have a monitor that supports multiple inputs, and switching to another input will also kill off all running apps (as does turning it off).

**Comment by dragynbane222** [comment]
> Yep, sounds like #679

It honestly doesn't appear to be that quite with that bug. Brodie seems to have encountered 2 bugs: 1 where all clients are closed when turning the monitor back on instead of moving the view to an empty workspace, and 1 where the latter is true.

I've only encountered the instance where the former is the issue, though it seems to be mitigated for the most part when I lock the screen before turning off the monitor, so I'm guessing it's some weird interaction between cosmic-comp and cosmic-greeter (I think cosmic-greeter handles the lock screen)

**Comment by dmac-au** [comment]
Having the same issue of all windows closing when I turn off my only monitor. 

I don't seem to notice any switching workspaces (probably because I only have one monitor), the panel shows one when I turn it back on an all processes seem to have quit. 

Noticed this in journalctl if it helps.

```shell
Nov 15 01:09:47 dmacarch cosmic-comp[89054]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:974
                                                0: <unknown>
                                                1: <unknown>
                                                2: <unknown>
                                                3: <unknown>
                                                4: <unknown>
                                                5: <unknown>
                                                6: <unknown>
                                                7: <unknown>
                                                8: <unknown>
                                                9: <unknown>
                                               10: <unknown>
                                               11: <unknown>
                                               12: <unknown>
                                               13: <unknown>
                                               14: <unknown>
                                               15: <unknown>
                                               16: <unknown>
                                               17: <unknown>
                                               18: <unknown>
                                               19: <unknown>
                                               20: __libc_start_main
                                               21: <unknown>
Nov 15 01:09:47 dmacarch cosmic-comp[89054]: thread 'surface-DP-3' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': src/backend/kms/surface/mod.rs:1124
                                                0: <unknown>
                                                1: <unknown>
                                                2: <unknown>
                                                3: <unknown>
                                                4: <unknown>
                                                5: <unknown>
                                                6: <unknown>
                                                7: <unknown>
                                                8: <unknown>
                                                9: <unknown>
                                               10: <unknown>
                                               11: <unknown>
                                               12: <unknown>
                                               13: <unknown>
                                               14: <unknown>
                                               15: <unknown>
                                               16: <unknown>
                                               17: <unknown>
Nov 15 01:09:47 dmacarch cosmic-comp[89054]: [EGL] 0x3008 (BAD_DISPLAY) eglDestroySync
Nov 15 01:09:47 dmacarch cosmic-comp[89054]: [EGL] 0x3008 (BAD_DISPLAY) eglTerminate
Nov 15 01:09:49 dmacarch cosmic-comp[90794]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Nov 15 01:09:49 dmacarch cosmic-comp[90794]: Key-Binding 'Period' only matched case insensitive for "period"
Nov 15 01:09:49 dmacarch cosmic-comp[90794]: Key-Binding 'Comma' only matched case insensitive for "comma"
Nov 15 01:09:49 dmacarch cosmic-comp[90794]: Key-Binding 'Period' only matched case insensitive for "period"
Nov 15 01:09:49 dmacarch cosmic-comp[90794]: Key-Binding 'Comma' only matched case insensitive for "comma"
Nov 15 01:09:49 dmacarch cosmic-comp[90794]: tiling exceptions custom config error: GetKey("tiling_exception_custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Nov 15 01:09:49 dmacarch cosmic-comp[90794]: Unable to become drm master, assuming unprivileged mode
```

**Comment by WatchMkr** [comment]
This issue appears to be fixed. I'll leave it open for a bit in case anyone is still seeing it.
