### ISSUE TITLE
Steam games cause cosmic to crash

### ISSUE THREAD

**Issue by aekobear** [pop-os/cosmic-comp#946]
With one of the recent updates (within the past week) all steam games are now causing cosmic to crash on a regular basis for me. I will boot up the steam game and 75% of the time, it will cause a complete crash and reboot of cosmic desktop (as if I had manually logged out and logged back in)

If I do manage to get a game running, there is a chance it will crash mid-gameplay as well.

In either case, the stacktrace in journalctl looks like this:

```
Oct 23 20:10:40 opal systemd[2134]: Failed to start app-cosmic-Deadlock-34890.scope - Application launched by COSMIC.
Oct 23 20:10:42 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:42 opal steam[3243]: fsync: up and running.
Oct 23 20:10:42 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:42 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:42 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:42 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:43 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:43 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:43 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:43 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:43 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:43 opal steam[3243]: wine: using kernel write watches, use_kernel_writewatch 1.
Oct 23 20:10:44 opal steam[3243]: Fossilize INFO: Autogroup scheduling is not enabled on this kernel. Will rely entirely on nice().
Oct 23 20:10:44 opal cosmic-comp[2235]: Toplevel for foreign-toplevel-list not registered for cosmic-toplevel-info.
Oct 23 20:10:44 opal cosmic-comp[2235]: thread 'main' panicked at 'Callback creating object zcosmic_toplevel_handle_v1@72[2] did not provide any object data.': /build/cosmic-comp-n3YWGp/cosmic-comp-0.1~1729619027~24.04~0092dac/vendor/wayland-backend/src/rs/server_impl/common_poll.rs:288
                                           0: <unknown>
                                           1: <unknown>
                                           2: <unknown>
                                           3: <unknown>
                                           4: <unknown>
                                           5: <unknown>
                                           6: <unknown>
                                           7: <unknown>
                                           8: <unknown>
                                           9: <unknown>
                                          10: <unknown>
                                          11: <unknown>
                                          12: <unknown>
                                          13: <unknown>
                                          14: __libc_start_main
                                          15: <unknown>
Oct 23 20:10:44 opal cosmic-comp[2235]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /build/cosmic-comp-n3YWGp/cosmic-comp-0.1~1729619027~24.04~0092dac/vendor/wayland-backend/src/rs/server_impl/handle.rs:179
                                           0: <unknown>
                                           1: <unknown>
                                           2: <unknown>
                                           3: <unknown>
                                           4: <unknown>
                                           5: <unknown>
                                           6: <unknown>
                                           7: <unknown>
                                           8: <unknown>
                                           9: <unknown>
                                          10: <unknown>
                                          11: <unknown>
                                          12: <unknown>
                                          13: <unknown>
                                          14: <unknown>
                                          15: <unknown>
                                          16: <unknown>
                                          17: <unknown>
                                          18: <unknown>
                                          19: __libc_start_main
                                          20: <unknown>
Oct 23 20:10:44 opal cosmic-comp[2235]: thread 'main' panicked at 'panic in a destructor during cleanup': library/core/src/panicking.rs:227
                                           0: <unknown>
                                           1: <unknown>
                                           2: <unknown>
                                           3: <unknown>
                                           4: <unknown>
                                           5: <unknown>
                                           6: <unknown>
                                           7: <unknown>
                                           8: <unknown>
                                           9: <unknown>
                                          10: <unknown>
                                          11: <unknown>
                                          12: <unknown>
                                          13: __libc_start_main
                                          14: <unknown>
Oct 23 20:10:44 opal xdg-desktop-por[2635]: Error reading events from display: Broken pipe
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: thread '<unnamed>' panicked at cosmic-applet-tiling/src/wayland.rs:151:55:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: thread '<unnamed>' panicked at cosmic-applet-tiling/src/wayland.rs:151:55:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: thread '<unnamed>' panicked at /build/cosmic-applets-89loiw/cosmic-applets-0.1.0~1729524303~24.04~11faa56/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: thread '<unnamed>' panicked at cosmic-applet-minimize/src/wayland_handler.rs:507:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: thread '<unnamed>' panicked at cosmic-applet-minimize/src/wayland_handler.rs:507:50:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: stack backtrace:
Oct 23 20:10:44 opal cosmic-session[2170]: Io error: Broken pipe (os error 32)
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletBluetooth: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTiling: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletAudio: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletTime: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNotifications: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletNetwork: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: thread 'main' panicked at cosmic-applet-minimize/src/lib.rs:125:21:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: Wayland Subscription ended...
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: thread 'main' panicked at cosmic-applet-minimize/src/lib.rs:125:21:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: Wayland Subscription ended...
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: stack backtrace:
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 23 20:10:44 opal cosmic-panel[2286]: process ' X_MINIMIZE_APPLET=true X_PRIVILEGED_WAYLAND_SOCKET=83 COSMIC_PANEL_NAME=Panel COSMIC_PANEL_SIZE=XS COSMIC_PANEL_OUTPUT=DP-2 COSMIC_PANEL_ANCHOR=Top COSMIC_PANEL_BACKGROUND=ThemeDefault RUST_BACKTRACE=1 WAYLAND_SOCKET=46 cosmic-applet-minimize ' failed with code 101
Oct 23 20:10:44 opal cosmic-panel[2286]: Exited with error code 101
Oct 23 20:10:44 opal cosmic-panel[2286]: process ' X_MINIMIZE_APPLET=true X_PRIVILEGED_WAYLAND_SOCKET=144 COSMIC_PANEL_NAME=Panel COSMIC_PANEL_SIZE=XS COSMIC_PANEL_OUTPUT=HDMI-A-2 COSMIC_PANEL_ANCHOR=Top COSMIC_PANEL_BACKGROUND=ThemeDefault RUST_BACKTRACE=1 WAYLAND_SOCKET=104 cosmic-applet-minimize ' failed with code 101
Oct 23 20:10:44 opal cosmic-panel[2286]: Exited with error code 101
Oct 23 20:10:44 opal systemd[2134]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
Oct 23 20:10:44 opal systemd[2134]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
Oct 23 20:10:44 opal systemd[2134]: xdg-desktop-portal-gtk.service: Consumed 1.555s CPU time.
Oct 23 20:10:44 opal cosmic-session[2170]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' terminated with signal 6
Oct 23 20:10:44 opal cosmic-session[2170]: cosmic-comp exited by signal
Oct 23 20:10:44 opal cosmic-session[2170]: draining stdin receiver before restarting process
Oct 23 20:10:44 opal cosmic-session[2170]: sleeping for 9ms before restarting process cosmic-comp (restart 0)
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(12v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(11v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(10v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(9v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(8v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(7v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(6v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(5v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(4v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(3v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: process 'ProcessKey(2v1)' cancelled
Oct 23 20:10:44 opal cosmic-session[2170]: RESTARTING: session restarted by request
```

I am running the latest cosmic alpha. I keep it pointed at popdev:master and update daily

**Comment by aekobear** [comment]
update: turns out this isn't caused by the games themselves, the crash happens when trying to launch games from the steam tray app, which makes sense given the nature of the bug and conversation in the wl-paste story

**Comment by Joomsy** [comment]
Same issue here, and it affects some games launched from inside Steam itself. Namely, 40K: Darktide, and this seems to be due to its launcher. If I use a launcher skip binary, the game runs just fine, and COSMIC doesn't crash. From what I can tell, it looks like this crash happens when a process transitions from one window to another that's owned by the same process. This is just me speculating on what I've noticed from the behavior, though.

All that being said, this bug also impacts things launched from the panel/dock if they're already running in the tray. Vesktop is a good example of this. Steam itself also suffers from this if you close it from the tray icon, and then try to relaunch it.

**Comment by Joomsy** [comment]
Looks like the crashing may have been fixed in `0.1~1729848475~24.04~eb64fda`, though, a new problem seems to have been introduced (or rather, returned). Thankfully, it still only affects Darktide, but it now acts like it's launching on a non-existent monitor. The game's launcher displays just fine, as expected, but the game's main window doesn't ever actually materialize. I can hear the sound from the game, but there's no icon on the panel, I can't Alt-Tab to it, and it's not making its way to a secondary workspace.

I don't mean to hijack this issue, and the only reason why I'm including this is because this same issue started up when `0.1~1729619027~24.04~0092dac` was pushed out last Tuesday. This was the update that initially started the crashing problem, and the problem I'm describing now was non-existent in Thursday's update to `0.1~1729786945~24.04~65a5470`. So, it seems like `0.1~1729848475~24.04~eb64fda` has a regression in it.

**Comment by aekobear** [comment]
agreed, looks like this is fixed by https://github.com/pop-os/cosmic-comp/pull/949 , I pulled the latest changes and no longer see the problem
