### ISSUE TITLE
 'attempt to subtract with overflow' on disconnect of output in debug build

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#952]
Not sure what specific circumstances caused this, but I had two external monitors mirrored, then detached both.

```
Oct 24 21:12:44 Superficies cosmic-comp[253013]: Udev event: type=remove, devnum=None devnode=None
Oct 24 21:12:44 Superficies cosmic-comp[253013]: Udev event: type=change, devnum=Some(57857) devnode=Some("/dev/dri/card1")
Oct 24 21:12:44 Superficies cosmic-comp[253013]: Device changed: #57857
Oct 24 21:12:48 Superficies cosmic-comp[253013]: thread 'main' panicked at 'attempt to subtract with overflow': src/backend/kms/device.rs:309
                                                    0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                              at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:422:9
                                                    1: log_panics::Config::install_panic_hook::{{closure}}
                                                              at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
                                                    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
                                                       std::panicking::rust_panic_with_hook
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:799:13
                                                    3: std::panicking::begin_panic_handler::{{closure}}
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:656:13
                                                    4: std::sys_common::backtrace::__rust_end_short_backtrace
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
                                                    5: rust_begin_unwind
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
                                                    6: core::panicking::panic_fmt
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
                                                    7: core::panicking::panic_const::panic_const_sub_overflow
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:179:21
                                                    8: cosmic_comp::backend::kms::device::<impl cosmic_comp::state::State>::device_changed
                                                              at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/backend/kms/device.rs:309:25
                                                    9: cosmic_comp::backend::kms::init_udev::{{closure}}
                                                              at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/backend/kms/mod.rs:240:49
                                                   10: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
                                                              at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/sources/mod.rs:327:61
                                                   11: <smithay::backend::udev::UdevBackend as calloop::sources::EventSource>::process_events
                                                              at /home/ian/.cargo/git/checkouts/smithay-0141b1fcb9e16729/05c49f7/src/backend/udev.rs:184:29
                                                   12: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                              at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/sources/mod.rs:326:9
                                                   13: calloop::loop_logic::EventLoop<Data>::dispatch_events
                                                              at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/loop_logic.rs:445:31
                                                   14: calloop::loop_logic::EventLoop<Data>::dispatch
                                                              at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/loop_logic.rs:550:9
                                                   15: calloop::loop_logic::EventLoop<Data>::run
                                                              at /home/ian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.14.1/src/loop_logic.rs:587:13
                                                   16: cosmic_comp::main
                                                              at /home/ian/src/pop/cosmic-epoch/cosmic-comp/src/main.rs:115:5
                                                   17: core::ops::function::FnOnce::call_once
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
                                                   18: std::sys_common::backtrace::__rust_begin_short_backtrace
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:155:18
                                                   19: std::rt::lang_start::{{closure}}
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:159:18
                                                   20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:284:13
                                                       std::panicking::try::do_call
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
                                                       std::panicking::try
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
                                                       std::panic::catch_unwind
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
                                                       std::rt::lang_start_internal::{{closure}}
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:141:48
                                                       std::panicking::try::do_call
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
                                                       std::panicking::try
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
                                                       std::panic::catch_unwind
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
                                                       std::rt::lang_start_internal
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:141:20
                                                   21: std::rt::lang_start
                                                              at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:158:17
                                                   22: main
                                                   23: __libc_start_call_main
                                                              at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
                                                   24: __libc_start_main_impl
                                                              at ./csu/../csu/libc-start.c:360:3
                                                   25: _start

```

**Comment by Drakulix** [comment]
Uh, the whole initial output placement logic needs a serious rework, but this should be less wrong now: https://github.com/pop-os/cosmic-comp/commit/520745315753b17526862ce44b10c0c8550a2ac6
